services:
  db-dev:
    container_name: postgres_go_dev
    image: postgres:16.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: link_db         
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"                  
    networks:
      - app-network
    profiles:
      - dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d link_db"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 10s

  # --- Приложение (prod-образ) ---
  app:
    build:
      context: .
      dockerfile: Dockerfile        
      target: prod                  
    ports:
      - "8081:8081"
    depends_on:
      db-dev:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://user:pass@db-dev:5432/link_db?sslmode=disable"
      APP_PORT: "8081"
    networks:
      - app-network
    profiles:
      - dev
      - prod

  db-test:
    container_name: postgres_go_test
    image: postgres:16.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: link_test        
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    networks:
      - app-network
    profiles:
      - test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d link_test"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 10s

  tester:
    build:
      context: .
      dockerfile: Dockerfile
      target: test                  
    depends_on:
      db-test:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://user:pass@db-test:5432/link_test?sslmode=disable"
    networks:
      - app-network
    profiles:
      - test

networks:
  app-network:
    driver: bridge

volumes:
  pgdata_dev:   
  pgdata_test:  
