services:
  postgres:
    container_name: postgres_go
    image: postgres:16.4
    restart: no
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DB: ${PGSQL_DBNAME}
      PGDATA: /data/postgres
    volumes:
      - pg-data:/data/postgres
    ports:
      - "${DB_PORT}:${PGSQL_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGSQL_USER} -d ${PGSQL_DBNAME}"]
      interval: 10s      
      timeout: 10s       
      retries: 20        
      start_period: 120s 

  uss-service:
    container_name: uss-service
    build:
      context: ./
      dockerfile: ./uss-service.dockerfile
    restart: always
    environment:
      APP_HOST: "${APP_HOST}"
      APP_PORT: "${APP_PORT}"
      DATABASE_URL: "postgresql://${PGSQL_USER}:${PGSQL_PASSWORD}@${PGSQL_HOST}:${PGSQL_PORT}/${PGSQL_DBNAME}?sslmode=${DB_SSLMODE}"
      # SECRET: "${SECRET}"
    env_file:
      - .secrets
    ports:
      - "${APP_PORT}:8081"
    depends_on:
      postgres:
        condition: service_healthy
  
volumes:
  pg-data:
